/* Copyright (C) 2009-2011 The Clashing Rocks Team */

/* This program is free software: you can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation, either version 3 of the License, or */
/* (at your option) any later version. */

/* This program is distributed in the hope that it will be useful, */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the */
/* GNU General Public License for more details. */

/* A sample ZeroMQ node which can act as subscriber */
/* Subscriber connects to broker's outbound socket */

#include <glib.h>       /* for GOptions*/
#include <pthread.h>   /* for threads */
#include <string.h>   /* for strlen()*/
#include <stdlib.h>  /* for exit()  */
#include <unistd.h> /* for read()  */
#include <fcntl.h> /* for open()  */

#include "config.h" /* Auto generated by the program */
#include "packedobjectsd.h"

static void *subscribe_data(void *sub_obj)
{
  subObject *sub_object;
  sub_object =  (subObject *) sub_obj; /* Casting void * pointer back to subObject pointer */

  while(1) {
    sub_object = receive_data(sub_object);
    if(sub_object->encode_type == ENCODED) {
      printf("Message received with encoding: %s \n",sub_object->message);
    } 
    else if(sub_object->encode_type == PLAIN) {
      printf("Message received without encoding: %s \n",sub_object->message);
    }
    else {
      printf("Message received but encoding status is unknown: %s \n",sub_object->message);
    }

    free(sub_object->message);
    usleep(1000 * 1000); /* Control receive frequency in microseconds. Also allows other thread to run.. */
  }

  /* We should never reach here unless something goes wrong! */
  return sub_object; 
}

int main (int argc, char *argv [])
{
  pthread_t thread_sub;
  gboolean verbose = FALSE;
  char *address = DEFAULT_SERVER_ADDRESS;
  char *sub_schema_path = "schema.xsd";
  int port = DEFAULT_SERVER_PORT;
  int recv_freq = DEFAULT_RECV_FREQ;
  subObject *sub_obj= NULL;

  /* For command line arguments */
  GError *error = NULL;
  GOptionContext *context;
  GOptionEntry entries[] = 
    {
      { "verbose", 'v', 0, G_OPTION_ARG_NONE, &verbose, "Verbose output", NULL },
      { "address", 'h', 0, G_OPTION_ARG_STRING, &address, "Lookup server address", NULL },
      { "port", 'p', 0, G_OPTION_ARG_INT, &port, "Lookup server port", "N" },
      { "recv-freq", 'r', 0, G_OPTION_ARG_INT, &recv_freq, "Receiving frequency for subscriber", "N" },
      { "sub-schema-path", 'y', 0, G_OPTION_ARG_STRING, &sub_schema_path, "File path for Subscriber xml schema", NULL },
      { NULL }
    };
 
  context = g_option_context_new ("- node");
  g_option_context_add_main_entries (context, entries, PACKAGE_NAME);
  
  if (!g_option_context_parse (context, &argc, &argv, &error)) {
    printf("option parsing failed: %s\n", error->message);
    exit (EXIT_FAILURE);
  }

  /* Initialise objects & variables */
  sub_obj = make_sub_object();
  
  sub_obj->port = port;
  sub_obj->address = malloc (strlen(address) + 1);
  sprintf(sub_obj->address, "%s",address);

  /* Connects to SUB socket, program quits if connect fails */ 
  sub_obj = subscribe_to_broker(sub_obj, sub_schema_path);
   
  /* Create thread which will execute subscribe_data() function */
  if (pthread_create( &thread_sub, NULL, subscribe_data,(void *) sub_obj)) {
    fprintf(stderr, "Error creating subscriber thread \n");
    exit(EXIT_FAILURE);
  } 


  /* Join the thread to start the server */
  if(pthread_join( thread_sub, NULL)) {
    fprintf(stderr, "Error joining subscriber thread \n");
    exit(EXIT_FAILURE);
  }


  /* We should never reach here unless something goes wrong! */
  return EXIT_FAILURE;
}
/* End of simple_subscriber.c */
